/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (BookController.as).
 */

package br.com.caelum.testeGranite.controller {

    import br.com.caelum.testeGranite.dao.BooksDao;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class BookControllerBase implements IExternalizable {

        private var _books:BooksDao;

        public function readExternal(input:IDataInput):void {
            _books = input.readObject() as BooksDao;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_books);
        }
    }
}