/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SessionCreator.as).
 */

package br.com.caelum.testeGranite.core {

    import br.com.caelum.vraptor.proxy.Proxifier;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.hibernate.Session;
    import org.hibernate.SessionFactory;

    [Bindable]
    public class SessionCreatorBase implements IExternalizable {

        private var _factory:SessionFactory;
        private var _proxifier:Proxifier;
        private var _session:Session;

        public function readExternal(input:IDataInput):void {
            _factory = input.readObject() as SessionFactory;
            _proxifier = input.readObject() as Proxifier;
            _session = input.readObject() as Session;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_factory);
            output.writeObject(_proxifier);
            output.writeObject(_session);
        }
    }
}